// ============================================================
// ZaraOS Built-in Skills Registry
//
// Declares every capability Zara knows about — built-in, mocked,
// and planned. These are capability declarations, not live integrations.
//
// SECURITY NOTE: No real email, SMS, call, delete, or external API
// calls are made from any skill in Alpha 0.1. All execution is mocked.
// Skills marked dangerous: true require explicit user confirmation.
// Skills marked future are declared only — execution returns a stub.
//
// Portability: No Replit services. No cloud dependencies.
// All storage is localStorage or in-memory only.
// ============================================================

import type { ZaraSkill } from "./types";

export const BUILTIN_SKILLS: ZaraSkill[] = [

  // ── COMMUNICATION ─────────────────────────────────────────

  {
    id: "skill.email",
    name: "Email",
    description: "Compose, send, and read email. Requires a configured email account. No account is connected by default.",
    category: "communication",
    status: "future",
    permissions: ["microphone", "network", "contacts"],
    voiceCommands: ["email John", "send email to Sarah", "read my emails", "check inbox"],
    textCommands: ["email [contact]", "send email to [contact]", "open inbox"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "Sending email transmits data externally. Confirm before sending.",
    localFirst: false,
    cloudOptional: false,
    providerRequired: "email_account",
    dangerous: false,
    enabled: false,
  },

  {
    id: "skill.text_messages",
    name: "Text Messages",
    description: "Send and receive SMS/MMS messages. Requires a connected phone or SIM-capable device.",
    category: "communication",
    status: "future",
    permissions: ["microphone", "network", "contacts"],
    voiceCommands: ["text Mike", "send a message to Alex", "read my texts"],
    textCommands: ["text [contact]", "send message to [contact]"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "Sending a text message transmits data to an external carrier. Confirm before sending.",
    localFirst: false,
    cloudOptional: false,
    providerRequired: "sms_account",
    dangerous: false,
    enabled: false,
  },

  {
    id: "skill.calls",
    name: "Phone Calls",
    description: "Place and receive voice calls. Requires a connected phone account or VoIP service.",
    category: "communication",
    status: "future",
    permissions: ["microphone", "network", "contacts"],
    voiceCommands: ["call Sarah", "place a call to John", "dial 555-1234"],
    textCommands: ["call [contact]", "dial [number]"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "Placing a call connects to an external network. Confirm before dialing.",
    localFirst: false,
    cloudOptional: false,
    providerRequired: "phone_account",
    dangerous: false,
    enabled: false,
  },

  {
    id: "skill.contacts",
    name: "Contacts",
    description: "Look up and manage contacts. Stored locally — no cloud sync by default.",
    category: "communication",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["find contact John", "add contact", "show my contacts", "look up Sarah"],
    textCommands: ["contacts", "find [name]", "add contact"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: true,
    dangerous: false,
    enabled: true,
  },

  // ── PRODUCTIVITY ─────────────────────────────────────────

  {
    id: "skill.timer",
    name: "Timers",
    description: "Set, manage, and cancel countdown timers. Runs locally with browser notifications.",
    category: "productivity",
    status: "mocked",
    permissions: ["notifications"],
    voiceCommands: ["set a timer for 10 minutes", "start a 30 second timer", "cancel timer"],
    textCommands: ["timer [duration]", "set timer for [duration]", "cancel timer"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.alarms",
    name: "Alarms",
    description: "Set recurring or one-time alarms. Persisted locally in localStorage.",
    category: "productivity",
    status: "mocked",
    permissions: ["notifications"],
    voiceCommands: ["set alarm for 7am", "wake me up at 6:30", "cancel my alarm"],
    textCommands: ["alarm [time]", "set alarm for [time]", "cancel alarm"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.calendar",
    name: "Calendar",
    description: "View, create, and manage calendar events. Local-first with optional cloud calendar sync.",
    category: "productivity",
    status: "mocked",
    permissions: ["notifications", "network"],
    voiceCommands: ["schedule meeting tomorrow at 2pm", "what's on my calendar", "add event", "show today's schedule"],
    textCommands: ["calendar", "schedule [event] at [time]", "show schedule"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: true,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.reminders",
    name: "Reminders",
    description: "Create context-aware reminders. Stored locally.",
    category: "productivity",
    status: "mocked",
    permissions: ["notifications"],
    voiceCommands: ["remind me to call John at 3pm", "add a reminder", "what are my reminders"],
    textCommands: ["remind me [task] at [time]", "reminders", "add reminder"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.notes",
    name: "Notes",
    description: "Create and manage text notes. Saved locally in plain text.",
    category: "productivity",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["take a note", "create note", "show my notes", "save this"],
    textCommands: ["new note", "open notes", "note [content]"],
    gestureCommands: ["PINCH: save note"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  // ── WEB & KNOWLEDGE ───────────────────────────────────────

  {
    id: "skill.web_search",
    name: "Search Web",
    description: "Search the internet. Requires network access. Query sent to chosen search engine — privacy-respecting options available.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["network"],
    voiceCommands: ["search the web for local AI models", "search for ZaraOS", "look up quantum computing"],
    textCommands: ["search [query]", "find [topic]", "look up [topic]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: false,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.fact_check",
    name: "Fact Check",
    description: "Cross-reference a claim against multiple sources. Uses local AI for analysis, optional network for source retrieval.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["local_ai", "network"],
    voiceCommands: ["fact check this", "is this true", "verify this claim"],
    textCommands: ["fact check [claim]", "verify [statement]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: true,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.summarize_page",
    name: "Summarize Page",
    description: "Summarize the active web page or document using local AI. Nothing leaves the device.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["local_ai"],
    voiceCommands: ["summarize this page", "summarize this article", "what is this about"],
    textCommands: ["summarize page", "summarize this", "tldr"],
    gestureCommands: ["TWO_FINGERS_UP: summarize visible content"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.research_topic",
    name: "Research Topic",
    description: "Deep-dive research on a topic using local AI and optional web sources.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["local_ai", "network"],
    voiceCommands: ["research topic machine learning", "deep dive on climate change", "teach me about quantum computing"],
    textCommands: ["research [topic]", "learn about [topic]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: true,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.translate",
    name: "Translate",
    description: "Translate text between languages. Uses local model by default; cloud optional for rare languages.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["local_ai"],
    voiceCommands: ["translate this to Spanish", "what does bonjour mean", "translate hello to Japanese"],
    textCommands: ["translate [text] to [language]", "translate to [language]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: true,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.define_term",
    name: "Define Term",
    description: "Look up definitions, synonyms, and etymology. Uses local dictionary first.",
    category: "web_knowledge",
    status: "mocked",
    permissions: ["local_ai"],
    voiceCommands: ["define ephemeral", "what does ubiquitous mean", "define recursion"],
    textCommands: ["define [word]", "what does [word] mean"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  // ── FILES & DOCUMENTS ─────────────────────────────────────

  {
    id: "skill.view_files",
    name: "View Files",
    description: "Browse and open local files. Requires file system permission.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["show my files", "open files", "browse documents folder"],
    textCommands: ["files", "open files", "browse [folder]"],
    gestureCommands: ["SWIPE_RIGHT: next file"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.edit_documents",
    name: "Edit Documents",
    description: "Open and edit documents using the local document editor.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["edit this document", "open document editor", "create new document"],
    textCommands: ["edit [file]", "new document", "open document"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.delete_files",
    name: "Delete Files",
    description: "Permanently delete files. Irreversible. Always requires explicit user confirmation.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files", "system_actions"],
    voiceCommands: ["delete this file", "remove file", "delete folder"],
    textCommands: ["delete [file]", "remove [file]"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "File deletion is permanent and cannot be undone. Confirm before deleting.",
    localFirst: true,
    cloudOptional: false,
    dangerous: true,
    enabled: true,
  },

  {
    id: "skill.rename_files",
    name: "Rename Files",
    description: "Rename files and folders.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["rename this file", "rename folder to archive"],
    textCommands: ["rename [file] to [new name]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.summarize_documents",
    name: "Summarize Documents",
    description: "Generate an AI summary of a local document. Runs fully on-device.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files", "local_ai"],
    voiceCommands: ["summarize this document", "summarize folder", "what is in this file", "extract key points"],
    textCommands: ["summarize [file]", "summarize document", "extract key points from [file]"],
    gestureCommands: ["TWO_FINGERS_UP: summarize selected"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.optimize_documents",
    name: "Optimize Documents",
    description: "Improve clarity, grammar, and structure of a document using local AI.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files", "local_ai"],
    voiceCommands: ["optimize this document", "improve this document", "clean up my writing"],
    textCommands: ["optimize [file]", "improve document", "edit and improve [file]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.organize_folders",
    name: "Organize Folders",
    description: "Auto-organize files into folders by type, date, or AI-suggested categories.",
    category: "files_documents",
    status: "mocked",
    permissions: ["files", "local_ai"],
    voiceCommands: ["organize my downloads folder", "sort files by type", "clean up this folder"],
    textCommands: ["organize [folder]", "sort files", "auto-organize"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "Organizing folders will move files. Review the plan before applying.",
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  // ── SYSTEM CONTROL ────────────────────────────────────────

  {
    id: "skill.open_app",
    name: "Open App",
    description: "Launch any ZaraOS module or installed application.",
    category: "system_control",
    status: "built_in",
    permissions: [],
    voiceCommands: ["open assistant", "open settings", "launch files", "open privacy"],
    textCommands: ["open [app]", "launch [app]", "go to [panel]"],
    gestureCommands: ["OPEN_PALM: open assistant", "SWIPE_LEFT/RIGHT: navigate panels"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.close_window",
    name: "Close Window",
    description: "Close the active panel and return to the dashboard.",
    category: "system_control",
    status: "built_in",
    permissions: [],
    voiceCommands: ["close this window", "go home", "close app"],
    textCommands: ["close", "go home", "dismiss"],
    gestureCommands: ["SWIPE_ACROSS: close active window", "FIST: dismiss"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.switch_panel",
    name: "Switch Panel",
    description: "Navigate between ZaraOS panels by name or direction.",
    category: "system_control",
    status: "built_in",
    permissions: [],
    voiceCommands: ["go to assistant", "switch to console", "navigate to settings", "next panel"],
    textCommands: ["navigate to [panel]", "switch to [panel]"],
    gestureCommands: ["SWIPE_LEFT: previous panel", "SWIPE_RIGHT: next panel"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.scroll",
    name: "Scroll Control",
    description: "Scroll content up or down, including precision scroll mode.",
    category: "system_control",
    status: "built_in",
    permissions: [],
    voiceCommands: ["scroll down", "scroll up", "scroll to top", "scroll to bottom"],
    textCommands: ["scroll down", "scroll up"],
    gestureCommands: ["SWIPE_UP: scroll down", "SWIPE_DOWN: scroll up", "TWO_FINGERS_UP: precision scroll"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.search_device",
    name: "Search Device",
    description: "Search across files, apps, and settings on the local device.",
    category: "system_control",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["search for budget report", "find my notes about AI", "locate file resume"],
    textCommands: ["search [query]", "find [file]", "locate [item]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.change_settings",
    name: "Change Settings",
    description: "Modify OS settings by voice or command.",
    category: "system_control",
    status: "mocked",
    permissions: ["system_actions"],
    voiceCommands: ["open settings", "change language", "switch input mode", "disable voice"],
    textCommands: ["settings", "change setting [name]", "configure [option]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.privacy_controls",
    name: "Privacy Controls",
    description: "Toggle hardware permissions and review active services.",
    category: "system_control",
    status: "built_in",
    permissions: ["system_actions"],
    voiceCommands: ["disable microphone", "turn off camera", "enable privacy mode", "show privacy status"],
    textCommands: ["privacy", "disable mic", "privacy status", "privacy controls"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  // ── MEDIA ─────────────────────────────────────────────────

  {
    id: "skill.play_audio",
    name: "Play Audio",
    description: "Play local audio files or streams.",
    category: "media",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["play music", "play audio", "start music", "play my playlist"],
    textCommands: ["play [file]", "play music", "start audio"],
    gestureCommands: ["OPEN_PALM: play / pause"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.pause_audio",
    name: "Pause Audio",
    description: "Pause currently playing audio.",
    category: "media",
    status: "mocked",
    permissions: [],
    voiceCommands: ["pause", "pause music", "stop audio", "pause playback"],
    textCommands: ["pause", "pause audio"],
    gestureCommands: ["FIST: pause"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.watch_video",
    name: "Watch Video",
    description: "Open and play local video files.",
    category: "media",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["play video", "open video", "watch movie", "watch video"],
    textCommands: ["play video", "open video [file]", "watch [file]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.volume_control",
    name: "Volume Control",
    description: "Adjust system audio volume.",
    category: "media",
    status: "mocked",
    permissions: ["system_actions"],
    voiceCommands: ["volume up", "volume down", "mute", "set volume to 50 percent"],
    textCommands: ["volume up", "volume down", "mute", "volume [level]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.next_track",
    name: "Next Track",
    description: "Skip to the next audio track.",
    category: "media",
    status: "mocked",
    permissions: [],
    voiceCommands: ["next track", "skip song", "next song", "skip"],
    textCommands: ["next", "next track", "skip"],
    gestureCommands: ["SWIPE_RIGHT: next track (media context)"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.previous_track",
    name: "Previous Track",
    description: "Go back to the previous audio track.",
    category: "media",
    status: "mocked",
    permissions: [],
    voiceCommands: ["previous track", "go back", "previous song", "replay"],
    textCommands: ["previous", "previous track", "back"],
    gestureCommands: ["SWIPE_LEFT: previous track (media context)"],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  // ── DEVELOPER ─────────────────────────────────────────────

  {
    id: "skill.build_app",
    name: "Build App",
    description: "Scaffold and build a new ZaraOS app or plugin using the Developer Portal.",
    category: "developer",
    status: "mocked",
    permissions: ["files", "system_actions"],
    voiceCommands: ["build me an app", "create a new plugin", "scaffold new app"],
    textCommands: ["build app", "new plugin", "scaffold [app name]"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.create_plugin",
    name: "Create Plugin",
    description: "Generate a new ZaraOS plugin manifest and starter template.",
    category: "developer",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["create a plugin", "new plugin template", "generate plugin manifest"],
    textCommands: ["create plugin", "new plugin", "plugin template"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.inspect_manifest",
    name: "Inspect Manifest",
    description: "View and validate a plugin or skill manifest file.",
    category: "developer",
    status: "mocked",
    permissions: ["files"],
    voiceCommands: ["inspect manifest", "validate plugin", "check plugin manifest"],
    textCommands: ["inspect manifest", "validate manifest", "check manifest"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.run_test",
    name: "Run Test",
    description: "Run tests for a plugin or skill in the sandbox.",
    category: "developer",
    status: "mocked",
    permissions: ["files", "system_actions"],
    voiceCommands: ["run tests", "test my plugin", "run unit tests"],
    textCommands: ["run test", "test [plugin]", "run tests"],
    gestureCommands: [],
    requiresConfirmation: false,
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: true,
  },

  {
    id: "skill.package_app",
    name: "Package App",
    description: "Bundle an app or plugin for distribution through the Zara Store.",
    category: "developer",
    status: "future",
    permissions: ["files", "system_actions"],
    voiceCommands: ["package my app", "build distribution bundle", "package plugin"],
    textCommands: ["package app", "bundle [app]", "package for store"],
    gestureCommands: [],
    requiresConfirmation: true,
    confirmationReason: "Packaging modifies build artifacts. Confirm before proceeding.",
    localFirst: true,
    cloudOptional: false,
    dangerous: false,
    enabled: false,
  },
];

// ── Registry helpers ───────────────────────────────────────
export function getSkillById(id: string): ZaraSkill | undefined {
  return BUILTIN_SKILLS.find((s) => s.id === id);
}

export function getSkillsByCategory(category: string): ZaraSkill[] {
  return BUILTIN_SKILLS.filter((s) => s.category === category);
}

export function getEnabledSkills(): ZaraSkill[] {
  return BUILTIN_SKILLS.filter((s) => s.enabled);
}

export function searchSkills(query: string): ZaraSkill[] {
  const q = query.toLowerCase();
  return BUILTIN_SKILLS.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.voiceCommands.some((c) => c.toLowerCase().includes(q)) ||
      s.textCommands.some((c) => c.toLowerCase().includes(q))
  );
}
