// ============================================================
// ZaraOS Conversation Memory Types
//
// Defines all memory structures for the AI Runtime.
//
// SECURITY RULES:
//   - No passwords stored in memory.
//   - No raw API keys stored in memory.
//   - No sensitive personal secrets stored in memory.
//   - All memory is local-only in Alpha 0.3.
//   - No cloud sync, no telemetry, no analytics.
//
// FUTURE: Alpha 0.4+ will add encrypted IndexedDB storage.
// FUTURE: Beta will add optional encrypted cloud backup
//         with user-generated keys (zero-knowledge).
// ============================================================

// ── Memory Scope ──────────────────────────────────────────
// session  — cleared when ZaraOS closes / tab is closed
// persistent — survives restarts, stored in localStorage
// pinned   — user-explicitly pinned, survives clearing
export type MemoryScope = "session" | "persistent" | "pinned";

// ── Memory Category ───────────────────────────────────────
export type MemoryCategory =
  | "conversation"     // Chat message history
  | "preference"       // User preference entries
  | "skill_usage"      // Which skills were recently used
  | "command_history"  // Raw command strings
  | "system"           // OS-level events stored as context
  | "context_note";    // Zara-authored notes about the session

// ── Individual Memory Entry ───────────────────────────────
export interface MemoryEntry {
  id: string;
  scope: MemoryScope;
  category: MemoryCategory;
  content: string;       // Plain text only — no binary, no raw secrets
  timestamp: number;
  pinned: boolean;
  tags: string[];
  sessionId: string;
}

// ── Conversation Message ──────────────────────────────────
// A single turn in the conversation history.
export interface ConversationMessage {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  timestamp: number;
  source?: "voice" | "gesture" | "keyboard" | "system" | "plugin";
  skillId?: string;    // If message relates to a skill execution
  intent?: string;     // Parsed command intent at time of message
  // AI metadata
  provider?: string;   // Which provider generated this response
  model?: string;      // Which model generated this response
  latencyMs?: number;  // How long the response took
  streamed?: boolean;  // Whether it was streamed
}

// ── Conversation Session ──────────────────────────────────
export interface ConversationSession {
  id: string;
  startedAt: number;
  lastActivityAt: number;
  messageCount: number;
  messages: ConversationMessage[];
  // Summary generated by AI after N messages (future)
  summary?: string;
}

// ── User Preferences (memory-persisted) ──────────────────
// SECURITY: No secrets here. Only behavioral preferences.
export interface UserPreferences {
  preferredProvider: string;          // e.g. "local"
  preferredModel: string;             // e.g. "zara-core-v0.1"
  localFirstEnabled: boolean;         // Always true by default
  offlineModeEnabled: boolean;        // Refuse cloud calls when true
  memoryEnabled: boolean;             // Whether to persist conversation
  conversationRetentionDays: number;  // How many days to keep history (0 = session only)
  preferredInputMode: string;         // "hybrid" | "voice" | "gesture" | "text"
  preferredGestureSet: string;        // Future: "default" | "custom"
  streamingEnabled: boolean;          // Show streaming responses
  contextInjectionEnabled: boolean;   // Inject OS context into prompts
}

// ── Memory Statistics ─────────────────────────────────────
export interface MemoryStats {
  totalEntries: number;
  sessionEntries: number;
  persistentEntries: number;
  pinnedEntries: number;
  conversationTurns: number;
  oldestEntryAge: number;  // ms since oldest entry
  estimatedTokens: number; // Rough estimate of context size
}

// ── Default User Preferences ─────────────────────────────
export const DEFAULT_USER_PREFERENCES: UserPreferences = {
  preferredProvider: "local",
  preferredModel: "zara-core-v0.1",
  localFirstEnabled: true,
  offlineModeEnabled: false,
  memoryEnabled: true,
  conversationRetentionDays: 7,
  preferredInputMode: "hybrid",
  preferredGestureSet: "default",
  streamingEnabled: true,
  contextInjectionEnabled: true,
};

// ── Skill Usage Record ────────────────────────────────────
export interface SkillUsageRecord {
  skillId: string;
  lastUsedAt: number;
  useCount: number;
  lastResult: "success" | "failed" | "cancelled" | "pending";
}
