// ============================================================
// ZaraOS Command Router
//
// Parses natural language input from any source and returns a
// structured ParsedCommand. The Zara Runtime then decides what
// to do with it (permission checks, destructive guards, routing).
//
// Input sources: voice, gesture, keyboard, system, plugin.
// All sources produce the same ParsedCommand — the runtime is
// source-agnostic by design.
//
// Gesture commands (e.g. "navigate to /assistant", "scroll down",
// "go home") are generated by gesture-mapper.ts and enter here
// like any other command. No separate gesture pipeline.
//
// Skill commands produce intent: "skill_action" with a skillId
// field so the Runtime can route directly to skillRuntime.
//
// Future: Replace keyword matching with a local intent classifier
// (small ONNX model or Ollama function-calling endpoint).
// ============================================================

import type { ParsedCommand, CommandIntent, InputSource } from "@/core/types";
import { PANEL_ORDER } from "./gesture-mapper";

// ── Keyword → Intent Map ──────────────────────────────────
interface IntentRule {
  keywords: string[];
  intent: CommandIntent;
  target?: string;
  skillId?: string;            // Populated for skill_action intents
  requiresPermission?: boolean;
  requiresConfirmation?: boolean;
  destructive?: boolean;
  baseConfidence?: number;
}

const INTENT_RULES: IntentRule[] = [
  // ── Navigation (gesture SWIPE_LEFT / SWIPE_RIGHT) ──────
  ...PANEL_ORDER.map((path) => ({
    keywords: [`navigate to ${path}`],
    intent: "navigation_action" as CommandIntent,
    target: path,
    requiresPermission: false,
    destructive: false,
    baseConfidence: 0.99,
  })),
  // Go home (SWIPE_ACROSS / FIST / text / voice). Consolidated from former duplicate rules.
  { keywords: ["go home", "close active window", "dismiss", "go to dashboard", "show dashboard", "home screen", "main screen"], intent: "navigation_action", target: "/", baseConfidence: 0.98 },

  // ── Scroll (gesture SWIPE_UP / SWIPE_DOWN / TWO_FINGERS_UP)
  { keywords: ["scroll down", "scroll up", "enable precision scroll", "precision scroll"], intent: "scroll_action", baseConfidence: 0.98 },

  // ── Open app / navigate ─────────────────────────────────
  { keywords: ["open browser", "launch browser", "start browser", "web browser"], intent: "open_app", target: "/apps", baseConfidence: 0.97 },
  { keywords: ["show files", "open files", "file explorer", "browse files"], intent: "open_app", target: "/files", baseConfidence: 0.97 },
  { keywords: ["open documents", "my documents", "create new document", "new doc"], intent: "open_app", target: "/files", baseConfidence: 0.95 },
  { keywords: ["play video", "open video", "watch video"], intent: "media_action", target: "/media", baseConfidence: 0.96 },
  { keywords: ["listen to audio", "play audio", "play music", "open music"], intent: "media_action", target: "/media", baseConfidence: 0.96 },
  { keywords: ["open settings", "go to settings", "show settings", "system settings"], intent: "settings_action", target: "/settings", baseConfidence: 0.97 },
  { keywords: ["open developer", "developer portal", "dev portal", "developer mode"], intent: "developer_action", target: "/developers", requiresPermission: true, baseConfidence: 0.95 },
  { keywords: ["ai providers", "open ai providers", "manage ai", "ai manager"], intent: "settings_action", target: "/ai-providers", baseConfidence: 0.94 },
  { keywords: ["open privacy", "privacy panel", "privacy settings", "show privacy", "privacy status"], intent: "privacy_action", target: "/privacy", baseConfidence: 0.97 },
  { keywords: ["open apps", "app launcher", "show apps", "launch app"], intent: "open_app", target: "/apps", baseConfidence: 0.95 },
  // OPEN_PALM gesture → wake Zara → open assistant
  { keywords: ["open assistant", "zara assistant", "talk to zara", "ask zara", "wake zara"], intent: "open_app", target: "/assistant", baseConfidence: 0.97 },
  { keywords: ["open console", "zara console", "command console"], intent: "open_app", target: "/console", baseConfidence: 0.96 },
  // Skills Hub
  { keywords: ["open skills", "skills hub", "zara skills", "show skills", "skill center", "what can zara do", "what can you do"], intent: "open_app", target: "/skills", baseConfidence: 0.97 },

  // ── Gesture meta-commands ───────────────────────────────
  { keywords: ["select", "select focused", "begin drag", "drag"], intent: "navigation_action", baseConfidence: 0.92 },

  // ── File actions ────────────────────────────────────────
  { keywords: ["summarize this folder", "summarize folder", "analyze folder", "scan folder"], intent: "skill_action", skillId: "skill.summarize_documents", requiresPermission: true, baseConfidence: 0.92 },
  { keywords: ["summarize this document", "summarize document", "summarize this file"], intent: "skill_action", skillId: "skill.summarize_documents", requiresPermission: true, baseConfidence: 0.93 },
  { keywords: ["optimize this document", "optimize document", "improve document", "clean up my writing"], intent: "skill_action", skillId: "skill.optimize_documents", requiresPermission: true, baseConfidence: 0.91 },
  { keywords: ["delete file", "remove file", "erase file", "delete this file"], intent: "skill_action", skillId: "skill.delete_files", requiresPermission: true, destructive: true, requiresConfirmation: true, baseConfidence: 0.93 },
  { keywords: ["view files", "show my files", "browse files", "open file browser"], intent: "skill_action", skillId: "skill.view_files", requiresPermission: true, baseConfidence: 0.91 },
  { keywords: ["edit document", "edit this document", "open document editor"], intent: "skill_action", skillId: "skill.edit_documents", requiresPermission: true, baseConfidence: 0.90 },
  { keywords: ["rename file", "rename this file"], intent: "skill_action", skillId: "skill.rename_files", requiresPermission: true, baseConfidence: 0.90 },
  { keywords: ["organize folder", "organize files", "organize my downloads"], intent: "skill_action", skillId: "skill.organize_folders", requiresPermission: true, requiresConfirmation: true, baseConfidence: 0.90 },

  // ── Communication skills ──────────────────────────────
  { keywords: ["email", "send email", "email john", "email sarah", "compose email"], intent: "skill_action", skillId: "skill.email", requiresPermission: true, requiresConfirmation: true, baseConfidence: 0.95 },
  { keywords: ["text", "send a message", "send text", "text mike", "text sarah"], intent: "skill_action", skillId: "skill.text_messages", requiresPermission: true, requiresConfirmation: true, baseConfidence: 0.94 },
  { keywords: ["call", "place a call", "call sarah", "dial"], intent: "skill_action", skillId: "skill.calls", requiresPermission: true, requiresConfirmation: true, baseConfidence: 0.95 },
  { keywords: ["find contact", "show contacts", "add contact", "my contacts"], intent: "skill_action", skillId: "skill.contacts", baseConfidence: 0.91 },

  // ── Productivity skills ───────────────────────────────
  { keywords: ["set a timer", "start a timer", "set timer", "timer for"], intent: "skill_action", skillId: "skill.timer", baseConfidence: 0.95 },
  { keywords: ["set alarm", "wake me up", "alarm for", "set an alarm"], intent: "skill_action", skillId: "skill.alarms", baseConfidence: 0.94 },
  { keywords: ["schedule meeting", "add event", "show my calendar", "what's on my calendar", "schedule"], intent: "skill_action", skillId: "skill.calendar", baseConfidence: 0.92 },
  { keywords: ["remind me", "add a reminder", "set a reminder", "what are my reminders"], intent: "skill_action", skillId: "skill.reminders", baseConfidence: 0.93 },
  { keywords: ["take a note", "create note", "new note", "save this note"], intent: "skill_action", skillId: "skill.notes", baseConfidence: 0.92 },

  // ── Web & Knowledge skills ────────────────────────────
  { keywords: ["search the web", "search web", "web search", "search for", "look up"], intent: "skill_action", skillId: "skill.web_search", baseConfidence: 0.94 },
  { keywords: ["fact check", "is this true", "verify this", "fact-check"], intent: "skill_action", skillId: "skill.fact_check", baseConfidence: 0.93 },
  { keywords: ["summarize this page", "summarize this article", "summarize page", "what is this about", "tldr"], intent: "skill_action", skillId: "skill.summarize_page", baseConfidence: 0.92 },
  { keywords: ["research topic", "research", "teach me about", "deep dive on"], intent: "skill_action", skillId: "skill.research_topic", baseConfidence: 0.90 },
  { keywords: ["translate", "translate to", "translate this"], intent: "skill_action", skillId: "skill.translate", baseConfidence: 0.93 },
  { keywords: ["define", "what does", "definition of", "what is the meaning"], intent: "skill_action", skillId: "skill.define_term", baseConfidence: 0.91 },

  // ── System control skills ─────────────────────────────
  { keywords: ["close this window", "close window", "close app"], intent: "skill_action", skillId: "skill.close_window", baseConfidence: 0.94 },
  { keywords: ["search device", "search my files", "find on this device"], intent: "skill_action", skillId: "skill.search_device", requiresPermission: true, baseConfidence: 0.91 },

  // ── Media skills ──────────────────────────────────────
  { keywords: ["pause", "stop playing", "stop media", "pause music"], intent: "skill_action", skillId: "skill.pause_audio", baseConfidence: 0.93 },
  { keywords: ["next track", "next song", "skip song", "skip"], intent: "skill_action", skillId: "skill.next_track", baseConfidence: 0.92 },
  { keywords: ["previous track", "previous song", "go back track"], intent: "skill_action", skillId: "skill.previous_track", baseConfidence: 0.91 },

  // ── System control — power ────────────────────────────
  { keywords: ["shut down", "shutdown", "power off", "turn off", "power down"], intent: "system_control", target: "shutdown", destructive: true, requiresConfirmation: true, baseConfidence: 0.97 },
  { keywords: ["restart", "reboot", "restart the computer", "reboot the system"], intent: "system_control", target: "reboot", destructive: true, requiresConfirmation: true, baseConfidence: 0.96 },
  { keywords: ["suspend", "sleep", "put to sleep", "hibernate", "standby"], intent: "system_control", target: "suspend", baseConfidence: 0.95 },
  { keywords: ["lock screen", "lock the screen", "lock computer", "lock session", "lock"], intent: "system_control", target: "lock", baseConfidence: 0.96 },

  // ── System control — volume ───────────────────────────
  { keywords: ["volume up", "louder", "increase volume", "turn it up", "raise volume"], intent: "system_control", target: "volume_up", baseConfidence: 0.94 },
  { keywords: ["volume down", "quieter", "decrease volume", "turn it down", "lower volume", "turn down"], intent: "system_control", target: "volume_down", baseConfidence: 0.94 },
  { keywords: ["mute", "silence", "mute audio", "mute the audio", "mute sound"], intent: "system_control", target: "mute", baseConfidence: 0.95 },
  { keywords: ["unmute", "unmute audio", "restore audio", "turn on sound"], intent: "system_control", target: "unmute", baseConfidence: 0.95 },
  { keywords: ["full volume", "max volume", "volume max", "maximum volume"], intent: "system_control", target: "volume_max", baseConfidence: 0.93 },

  // ── System control — brightness ───────────────────────
  { keywords: ["brighter", "increase brightness", "brightness up", "turn up brightness", "more brightness"], intent: "system_control", target: "brightness_up", baseConfidence: 0.93 },
  { keywords: ["dimmer", "decrease brightness", "brightness down", "dim screen", "less brightness", "lower brightness"], intent: "system_control", target: "brightness_down", baseConfidence: 0.93 },
  { keywords: ["full brightness", "max brightness", "brightness max", "brightest"], intent: "system_control", target: "brightness_max", baseConfidence: 0.91 },

  // ── System control — wifi ─────────────────────────────
  { keywords: ["scan wifi", "scan for wifi", "show wifi networks", "list wifi", "available networks", "what wifi"], intent: "system_control", target: "wifi_scan", baseConfidence: 0.93 },
  { keywords: ["disconnect wifi", "disconnect from wifi", "turn off wifi", "disable wifi"], intent: "system_control", target: "wifi_disconnect", baseConfidence: 0.94 },

  // ── Developer skills ──────────────────────────────────
  { keywords: ["build me an app", "build an app", "create a new app", "scaffold app"], intent: "skill_action", skillId: "skill.build_app", requiresPermission: true, baseConfidence: 0.93 },
  { keywords: ["create a plugin", "new plugin", "plugin template", "create plugin"], intent: "skill_action", skillId: "skill.create_plugin", requiresPermission: true, baseConfidence: 0.92 },
  { keywords: ["inspect manifest", "validate plugin", "check manifest"], intent: "skill_action", skillId: "skill.inspect_manifest", baseConfidence: 0.91 },
  { keywords: ["run tests", "run test", "test my plugin", "run unit tests"], intent: "skill_action", skillId: "skill.run_test", requiresPermission: true, baseConfidence: 0.92 },

  // ── Search ──────────────────────────────────────────────
  { keywords: ["search files", "find file", "look for file"], intent: "search", requiresPermission: true, baseConfidence: 0.91 },

  // ── System status ────────────────────────────────────────
  { keywords: ["system status", "how is the system", "check status", "system health", "show stats"], intent: "system_status", target: "/", baseConfidence: 0.95 },
  { keywords: ["what is running", "active processes", "show processes"], intent: "system_status", baseConfidence: 0.90 },

  // ── Privacy ──────────────────────────────────────────────
  { keywords: ["enable microphone", "turn on mic", "enable mic", "activate mic"], intent: "privacy_action", target: "/privacy", requiresPermission: true, baseConfidence: 0.96 },
  { keywords: ["disable microphone", "turn off mic", "disable mic"], intent: "privacy_action", target: "/privacy", baseConfidence: 0.96 },
  { keywords: ["enable camera", "turn on camera", "activate camera"], intent: "privacy_action", target: "/privacy", requiresPermission: true, baseConfidence: 0.96 },
  { keywords: ["disable camera", "turn off camera"], intent: "privacy_action", target: "/privacy", baseConfidence: 0.96 },
  { keywords: ["enable cloud ai", "turn on cloud", "use cloud"], intent: "privacy_action", target: "/ai-providers", requiresPermission: true, baseConfidence: 0.94 },

  // ── Memory ───────────────────────────────────────────────
  { keywords: ["open memory", "show memory", "memory panel", "zara memory", "memory settings", "view memory"], intent: "open_app", target: "/memory", baseConfidence: 0.97 },
  { keywords: ["clear memory", "clear conversation", "reset memory", "clear chat"], intent: "privacy_action", target: "/memory", requiresConfirmation: true, destructive: true, baseConfidence: 0.94 },
  { keywords: ["purge memory", "purge all memory", "delete all memory", "wipe memory"], intent: "privacy_action", target: "/memory", requiresConfirmation: true, destructive: true, baseConfidence: 0.96 },
  { keywords: ["disable memory", "turn off memory", "stop remembering"], intent: "privacy_action", target: "/memory", baseConfidence: 0.94 },
  { keywords: ["enable memory", "turn on memory", "start remembering"], intent: "privacy_action", target: "/memory", baseConfidence: 0.94 },

  // ── Local AI ─────────────────────────────────────────────
  { keywords: ["show local ai", "local ai status", "ai status", "show ai status"], intent: "system_status", target: "/ai-providers", baseConfidence: 0.95 },
  { keywords: ["test ollama", "check ollama", "ollama status", "is ollama running"], intent: "settings_action", target: "/ai-providers", baseConfidence: 0.96 },
  { keywords: ["show models", "list models", "available models", "installed models", "what models"], intent: "settings_action", target: "/ai-providers", baseConfidence: 0.93 },
  { keywords: ["switch model", "change model", "use model", "select model"], intent: "settings_action", target: "/ai-providers", baseConfidence: 0.92 },

  // ── Developer ────────────────────────────────────────────
  { keywords: ["enable developer mode", "dev mode on", "toggle developer"], intent: "developer_action", target: "/developers", requiresPermission: true, baseConfidence: 0.95 },
  { keywords: ["install plugin", "add plugin", "load plugin"], intent: "developer_action", requiresPermission: true, baseConfidence: 0.91 },
];

// ── Mocked Responses by Intent ────────────────────────────
const INTENT_RESPONSES: Record<CommandIntent, (cmd: ParsedCommand) => string> = {
  open_app:          (c) => `Opening ${c.target?.replace("/", "") || "application"}...`,
  close_app:         (c) => `Closing ${c.target || "application"}.`,
  navigation_action: (c) => c.target ? `Navigating to ${c.target}.` : `Navigation command received.`,
  scroll_action:     (c) => `Scroll: ${c.raw}.`,
  search:            (c) => `Initiating search: "${c.raw}"`,
  file_action:       () => `Analyzing folder contents...\nFound 12 files — 3 documents, 9 media files. Total: 1.2 GB.`,
  media_action:      (c) => `Media command: ${c.raw}.`,
  ai_question:       (c) => `Routing to Zara AI: "${c.raw}"`,
  system_status:     () => `System nominal. CPU: 14% | RAM: 3.2/16 GB | Local AI: Active.`,
  privacy_action:    (c) => `Privacy command: ${c.raw}. Check the Privacy panel to confirm.`,
  settings_action:   () => `Opening system settings.`,
  developer_action:  () => `Developer mode activated. Access the Developer Portal for advanced tools.`,
  skill_action:      (c) => `Routing to skill: ${c.skillId ?? "unknown"}`,
  system_control:    (c) => {
    const labels: Record<string, string> = {
      shutdown: "Shutting down...",
      reboot: "Restarting...",
      suspend: "Suspending system...",
      lock: "Locking screen...",
      volume_up: "Volume increased.",
      volume_down: "Volume decreased.",
      mute: "Audio muted.",
      unmute: "Audio unmuted.",
      volume_max: "Volume set to maximum.",
      brightness_up: "Brightness increased.",
      brightness_down: "Brightness decreased.",
      brightness_max: "Brightness set to maximum.",
      wifi_scan: "Scanning for Wi-Fi networks...",
      wifi_disconnect: "Disconnecting from Wi-Fi...",
    };
    return labels[c.target ?? ""] ?? `System control: ${c.target ?? c.raw}`;
  },
  unknown:           (c) => `Command not recognized: "${c.raw}". Try "open settings" or "show files".`,
};

// ── Classifier ────────────────────────────────────────────
function classify(normalized: string): { rule: IntentRule | null; confidence: number } {
  let bestRule: IntentRule | null = null;
  let bestScore = 0;

  for (const rule of INTENT_RULES) {
    for (const keyword of rule.keywords) {
      if (normalized.includes(keyword)) {
        const score = rule.baseConfidence ?? 0.88;
        if (score > bestScore) {
          bestScore = score;
          bestRule = rule;
        }
      }
    }
  }

  // Heuristic: ends with "?" or starts with a question word → AI question
  if (
    !bestRule &&
    (normalized.endsWith("?") ||
      /^(what|who|how|why|when|where|is|can|does|will|tell me|explain)/.test(normalized))
  ) {
    return { rule: null, confidence: 0.85 };
  }

  return { rule: bestRule, confidence: bestScore };
}

// ── Public API ────────────────────────────────────────────
export function parseAndRoute(raw: string, source: InputSource = "keyboard"): ParsedCommand {
  const normalized = raw.trim().toLowerCase();
  const { rule, confidence } = classify(normalized);

  const isQuestion = !rule && confidence === 0.85;

  const intent: CommandIntent = isQuestion
    ? "ai_question"
    : rule
    ? rule.intent
    : "unknown";

  return {
    raw,
    normalized,
    intent,
    target: rule?.target,
    skillId: rule?.skillId,
    source,
    requiresPermission: rule?.requiresPermission ?? false,
    requiresConfirmation: rule?.requiresConfirmation ?? false,
    destructive: rule?.destructive ?? false,
    confidence: rule ? confidence : isQuestion ? 0.85 : 0.1,
  };
}

export function getResponseText(cmd: ParsedCommand): string {
  return INTENT_RESPONSES[cmd.intent](cmd);
}

// ── Legacy compat ─────────────────────────────────────────
export interface CommandResponse {
  output: string;
  action?: string;
  payload?: string;
}

export function routeCommand(input: string): CommandResponse {
  const cmd = parseAndRoute(input, "keyboard");
  return {
    output: getResponseText(cmd),
    action: cmd.target ? "navigate" : undefined,
    payload: cmd.target,
  };
}
